Update scalaz version to 7.2.6
gakuzzzz/free-scalikejdbc pull request #5
Opened 2016-09-25 13:20 UTC by shinnya

Hi, @gakuzzzz.

I've used free-scalikejdbc for my commercial products and want to update scalaz version for some reason. But scalaz doesn't provide `FreeC` type anymore from `7.3`. So I fixed the code to make all unit tests green.

I updated the scalaz version to the latest and is it OK for you?

See this commit for more detail:
https://github.com/scalaz/scalaz/commit/783eb0ed7f6aec56d6245e9b2b9bac97aab74d22.

Sincerely.

2016-09-29 04:18 UTC, shinnya commented
I would be happy if you could review in a day or two 😄

2016-09-29 09:59 UTC, xuwei-k requested changes
inconsistent scalaz-stream version

2016-09-29 09:59 UTC, xuwei-k commented on build.sbt
> +    ("org.scalaz.stream"       %% "scalaz-stream"                    % "0.8.4") ::
```scala
"org.scalaz.stream"  %% "scalaz-stream" % "0.8.4a"
```

https://oss.sonatype.org/content/repositories/releases/org/scalaz/stream/scalaz-stream_2.11/0.8.4a/scalaz-stream_2.11-0.8.4a.pom
https://oss.sonatype.org/content/repositories/releases/org/scalaz/stream/scalaz-stream_2.11/0.8.4/scalaz-stream_2.11-0.8.4.pom

2016-09-29 10:16 UTC, shinnya commented on build.sbt
> +    ("org.scalaz.stream"       %% "scalaz-stream"                    % "0.8.4") ::
Thanks. I'll update scalaz-stream to 0.8.4a and scalaz-* to 7.2.5.

2016-09-29 23:42 UTC, shinnya commented on build.sbt
> +    ("org.scalaz.stream"       %% "scalaz-stream"                    % "0.8.4") ::
fixed

2016-10-02 16:50 UTC, gakuzzzz commented
@shinnya sorry my late reply.

This PR LGTM!!

I want to merge this. however it conflicts #4.
Would you solve it? 
I'll merge after it.

thanks!

2016-10-02 16:51 UTC, shinnya commented
@gakuzzzz Ok. I'll fix soon.

2016-10-02 17:03 UTC, gakuzzzz commented
thanks a lot!!

2016-10-02 17:03 UTC, merged

2016-10-02 17:04 UTC, shinnya commented
Thank you :smile:

2016-10-02 17:10 UTC, shinnya commented
@gakuzzzz BTW, when are you going to publish a new vertion to Maven Central? I would appriciate it if you could publish as soon as possible.

2016-10-02 17:14 UTC, shinnya commented
Oops. I forgot that free-scalikejdbc was not registered on Maven Central. Sorry.

2016-10-02 18:12 UTC, gakuzzzz commented
yah, free-scalikejdbc is a Proof of Concept. there are no plans to publish into maven central.